version: "3.3"
services:
  mariadb:
    image: mariadb:10.1.44
    container_name: mariadb-10
    restart: "no" # options: no, always, on-failure, unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./data-mysql:/var/lib/mysql # mysql data mounting point
      - ./sql:/root/sql # sql for export/import
    ports:
      - 3306:3306

  postgres:
    image: postgres:10.12
    container_name: postgres-10
    restart: "no"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    volumes:
      - ./data-postgres:/var/lib/postgresql/data # postgres data mounting point
      - ./sql:/root/sql # sql for export/import
    ports:
      - 5432:5432
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"

  mongo:
    image: mongo:4.2.3
    container_name: mongo-4.2.3
    restart: "no"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data-mongo:/data/db # mongo data mounting point
      - ./sql:/root/sql # sql for export/import

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: "no"
  #   ports:
  #     - 9091:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: user
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password

pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    restart: "no"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@password.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 2345:80

spark:
  image: docker.io/bitnami/spark:3
  container_name: spark-master
  environment:
    - SPARK_MODE=master
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
  ports:
    - '8080:8080'


spark-worker:
  image: docker.io/bitnami/spark:3
  container_name: spark-worker
  environment:
    - SPARK_MODE=worker
    - SPARK_MASTER_URL=spark://spark:7077
    - SPARK_WORKER_MEMORY=1G
    - SPARK_WORKER_CORES=1
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
  ports:
    - '8081:8081'
